### ISSUE TITLE
No Texture

### ISSUE THREAD

**Issue by Language-Changer** [MandC-Studio/Basic-Technology-Fabric#1]
Where is our texture?

# WHERE?

Do you know how I want?
En?

---

@Muxue1230

**Comment by MandC-Studio** [comment]
cnm(ʘдʘ╬)

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dorion Y. Chou ***@***.***>
发送时间: Monday, June 10, 2024 2:01:57 PM
收件人: MandC-Studio/Basic-Technology-Fabric ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MandC-Studio/Basic-Technology-Fabric] No Texture (Issue #1)


Where is our texture?

WHERE?

Do you know how I want?
En?

________________________________

@MuXue1230<https://github.com/MuXue1230>

**Comment by MandC-Studio** [comment]
**Sorry, we don't have textures at the moment.**

But we probably need at least 2 weeks before we start making it.

There's nothing i can do about it. Sorry for that.
